server:
  port: 7001

#配置为Eureka的服务端-服务注册中心
eureka:
  instance:
    hostname: eureka7001.com   #eureka注册的服务端实例名
  client:
    register-with-eureka: false    #是否注册自己，false表示不注册
    fetch-registry: false   #自己就是注册中心，职责就是维护实例不需要检索服务。
    #设置uereka交互的地址，查询注册的服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/
# 关闭自我保护机制那堆红字，默认为true，是开启的,下边设置超时心跳时间，默认90秒，现在改为2秒
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000