server:
  port: 8080

spring:
  redis:
    cluster:
      nodes:
        - 192.168.2.10:6379 #替换为正确的redis集群的IP和端口号
        - 192.168.2.10:6380 #替换为正确的redis集群的IP和端口号
        - 192.168.2.11:6379 #替换为正确的redis集群的IP和端口号
        - 192.168.2.11:6380 #替换为正确的redis集群的IP和端口号
        - 192.168.2.12:6379 #替换为正确的redis集群的IP和端口号
        - 192.168.2.12:6380 #替换为正确的redis集群的IP和端口号
      connectionTimeout: 6000
      soTimeout: 6000
      maxAttempts: 5
      password: root #写正确的密码
#spring:
#  redis:
#    sentinel:
#      master: mymaster
#      nodes: 10.100.1.29:8881,10.100.1.29:8883,10.100.1.29:8882
#    #host: 10.100.1.29
#    password: bangsun
#    #port: 6380
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池中的最小空闲连接
#        max-idle: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 100000
#    # 连接超时时间（毫秒）
#    timeout: 5000
#    #默认是索引为0的数据库
#    database: 0
suaf:
  test:
    name: zhangsan
    age: 23