###################以下为Redis增加的配置###########################
spring:
  redis:
    #单机配置
    #host: 192.168.43.188
    #port: 6379
    timeout: 6000
    password: bangsun
    ###################以下为redis哨兵增加的配置###########################
    sentinel:
      nodes: 10.100.1.29:8881,10.100.1.29:8882,10.100.1.29:8883
      master: mymaster
    ###################以下为lettuce连接池增加的配置###########################
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制
  ###################以下为springcache增加的配置###########################
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s
server:
  port: 8088